### ISSUE TITLE
Toolbar out of the screen

### ISSUE THREAD

**Issue by pirakleous** [liuguangqiang/AndroidSupportDesignSample#1]
Hello thank you for the great sample. But when i run it on nexus 5 i face the problem shown in the picture. The toolbar is out of the screen.
![screen shot 2015-06-03 at 02 48 41](https://cloud.githubusercontent.com/assets/8356922/7949847/38544336-099b-11e5-917b-1a8fb6fa719b.png)

Why is that happening?

**Comment by liuguangqiang** [comment]
Hi ! I run the sample on Nexus 5(Android 5.1) is working fine. What android version is on your Nexus 5?

**Comment by pirakleous** [comment]
I use this emulator
![screen shot 2015-06-03 at 10 30 07](https://cloud.githubusercontent.com/assets/8356922/7954821/921b500e-09db-11e5-9b33-b5512e4dbac3.png)

**Comment by derohimat** [comment]
i found the same problem at zenfone 5 Lollipop version
![screenshot_2015-06-03-17-44-30](https://cloud.githubusercontent.com/assets/3787041/7958332/7b6469c6-0a18-11e5-9eed-9232c2e5696f.jpg)

**Comment by ghatasheh** [comment]
I faced the same problem when I used translucent status bar, I solved it by adding padding top to the Toolbar.
dimens.xml : `<dimen name="toolbar_padding_top">0dp</dimen>`
dimens.xml v19 : `<dimen name="toolbar_padding_top">24dp</dimen>`
dimens.xml v21: `<dimen name="toolbar_padding_top">24dp</dimen>`

**Comment by pirakleous** [comment]
No i get this
![screen shot 2015-06-03 at 15 36 56](https://cloud.githubusercontent.com/assets/8356922/7960083/75d5b828-0a06-11e5-8818-ff5fbdd91710.png)

**Comment by ghatasheh** [comment]
@panagorn did you add it to the toolbar, like this:
 `<Toolbar android:paddingTop="@dimen/toolbar_padding_top" />`

**Comment by pirakleous** [comment]
yes

**Comment by liuguangqiang** [comment]
@panagorn @ghatasheh ,Hi ! I have run the sample on many devices are working fine.Do you change the code or layout? Or maybe it is a compatibility problem about the design support library.

**Comment by Suleiman19** [comment]
I face the same problem as well. It works perfectly fine on pre Lolliop (JB 4.2.2). But on Lollipop, I get the same issue as @panagorn . And no, @ghatasheh your solution didn't work either. 
For Lollipop, I'm using GenyMotion emulator Google Nexus 5 5.0.0

@panagorn Since we face the same issue, I will be posting this on stackoverflow, try to get a speedy solution to this.

**Comment by kosev** [comment]
Hello there. I have the same issue on Moto X with 5.0 and on emulator with 5.1.
I found this example http://blog.grafixartist.com/toolbar-animation-with-android-design-support-library/ and it has the same issue but it is not on the screenshots and videos on the blog, only when I run the sample. Maybe it is a bug in current support design lib.

**Comment by andyolivares** [comment]
Hello, I have the same problem with Samsung Galaxy S6 with Android Lollipop 5.0.2.
It works fine with a Galaxy Nexus with Android KitKat 4.3.

**Comment by Suleiman19** [comment]
Hi @kosev, that link is my blog :-) experiencing the same issue myself. The output is from a JellyBean device.

I did not mention the error because:
1. Not everyone is experiencing it
2. I've cross checked with Chris Bane's cheesesquare sample app, to make sure
3. It works perfectly fine on pre Lollipop
4. Making the Status Bar overlap with fitsSystemWindows, seems to be the problem.

So my suggestion to you is to either give up the transparent Status Bar. Or fallback to a custom implementation without the Design Library. Being relatively new, the library is bound to have such issues. Our only option is to wait until we get some support.

Regards

**Comment by niko001** [comment]
This is a bug in the Design Support Library, please see [here](https://code.google.com/p/android/issues/detail?id=175069)

**Comment by Suleiman19** [comment]
Thanks for that @niko001 Good to hear!

**Comment by ydcool** [comment]
The bug has been fixed in 23.0.0. So this issue should be closed.
